# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 14a4a364125376fab8b4d2ff2e897bf4da4c20d3e8765854c6b3a4e7e4351cb586736cbb74175e59682cc82d9fe1d3063f12ebe0e3f11f69d03f3895b27fa121

test:
  secret_key_base: f8b8632a8e00fff45033efd4a031cc490df7e7142b9211a5ee70225618e24b13df3c1323f119ea86115e8c50df6259b4de6941e84b9cc7068a202bd6c66717dc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
